<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>4ae95087-da2e-4c04-83f8-514c828c6a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.imageContainer__tvs1t > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drag-zone-customImage']/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;add-image Upload profile picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0ad50de-c04f-4bd5-b530-1c3ba76a1131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-zone-customImage&quot;)/div[@class=&quot;upload__OTyr_&quot;]/button[@class=&quot;imageContainer__tvs1t&quot;]/div[1]</value>
      <webElementGuid>7179b50a-8055-465a-8be2-0471eec406bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drag-zone-customImage']/div/button/div</value>
      <webElementGuid>20b417bb-c501-46f8-a9dc-a7ecaec31ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/following::div[9]</value>
      <webElementGuid>9bdd9bd9-af83-4102-9b84-c302c07167e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[10]</value>
      <webElementGuid>5c820bf0-35ba-4d5a-8463-ded954ce5218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload profile picture'])[1]/preceding::div[1]</value>
      <webElementGuid>1bc5bab1-6814-4bf7-94af-58dbe0a37811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>b0198234-c9f2-486b-8c75-45a326203304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
