<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ANALYZEghfgfxcg19 versions</name>
   <tag></tag>
   <elementGuidId>f9e3f29b-103a-460a-9ba9-3d86347522af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.subCategoryTile__qklai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/div[2]/ul/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ANALYZEghfgfxcg19 versions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14da95ea-86ef-4966-8d7f-7fb8dc782934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subCategoryTile__qklai</value>
      <webElementGuid>ea8020e9-fdfa-417a-bd28-bf71b85bcee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ANALYZEghfgfxcg19 versions</value>
      <webElementGuid>e013e647-9c28-4193-9100-b6011b0490ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;containtManagementDetailsWrapper__VIyoK&quot;]/div[@class=&quot;subCategoriesWrapper__BciwA&quot;]/div[1]/div[@class=&quot;subCategoryTabWrapper__XbXUh&quot;]/div[@class=&quot;listInfo__lK6lU&quot;]/ul[1]/li[@class=&quot;active__O6cn1&quot;]/div[@class=&quot;subCategoryTile__qklai&quot;]</value>
      <webElementGuid>f554cd5d-6247-4278-9d4b-cdf455bbb424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div[2]/ul/li/div</value>
      <webElementGuid>60486f3d-db20-43ff-b8f4-0142f3af4b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUB-CATEGORIES (9)'])[1]/following::div[2]</value>
      <webElementGuid>d059449a-e74b-45c4-82f4-8ac0933d6d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[1]/following::div[6]</value>
      <webElementGuid>297ac825-30f1-4a27-9766-6adf261a7d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BETWEEN'])[1]/preceding::div[1]</value>
      <webElementGuid>e4af90b3-5a14-4b6f-91aa-f07d37186d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div</value>
      <webElementGuid>92953c15-c498-49d6-923c-9cb6482a975c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ANALYZEghfgfxcg19 versions' or . = 'ANALYZEghfgfxcg19 versions')]</value>
      <webElementGuid>07ebb2c3-01e7-4c49-9772-90cd2ebd8957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
