<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__subCategory</name>
   <tag></tag>
   <elementGuidId>86175938-68e0-4985-b9a2-3d062c10ddb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter sub category&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15fe73b9-2c81-4e0d-86d2-baf8284eb12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subCategory</value>
      <webElementGuid>a13ebb7b-322b-404b-98ec-4aefa1f94a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b44ed01-1fce-4654-84a4-47d848299229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subCategory</value>
      <webElementGuid>d13554ab-7b4b-4f06-8968-720b39ddcdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter sub category</value>
      <webElementGuid>abc2970e-8556-4878-97bb-3768c42a95c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f72cedfb-df1c-4a05-b096-2503f2d6fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2fb84abc-11a7-4a19-9524-4af64c4a5326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>subcat2</value>
      <webElementGuid>9b081cf2-34d8-43dc-a8cd-c2d46e0c8556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subCategory&quot;)</value>
      <webElementGuid>c76d6fbf-41ed-49c0-9fac-9319a064a87a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subCategory']</value>
      <webElementGuid>cf1b4e5a-649b-4afb-9b19-81996d1ba43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>dda8dd56-e755-4ae5-9026-3c891cffd0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d72d4cda-b593-44d9-a033-1a3a7fbbce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'subCategory' and @type = 'text' and @name = 'subCategory' and @placeholder = 'Enter sub category']</value>
      <webElementGuid>e013cda8-7da2-4291-9e68-c58433c07832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
