<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category_machineCategory</name>
   <tag></tag>
   <elementGuidId>0259064b-7c68-4a76-bc0f-14762c7350f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#machineCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='machineCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter category name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b89aa0e8-71f7-477d-932d-f6c4c4291835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>machineCategory</value>
      <webElementGuid>f79bcfd6-0ec5-470f-8fbd-9eee905a3c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e00f59f-bda4-4d33-b6da-eaa87ada74b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>machineCategory</value>
      <webElementGuid>114022db-8fa1-4df5-8382-3def618fff62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter category name</value>
      <webElementGuid>8e703fef-8b8b-401f-a5cc-4a9c1a4572e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>252e3a04-54da-4107-a9de-e9b90c2a5be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ac808876-c77f-4e63-a5aa-f3f22e830dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cat  One</value>
      <webElementGuid>242d665b-1547-4f2d-8b00-63676a7547f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;machineCategory&quot;)</value>
      <webElementGuid>88a93349-ad42-4328-ba9d-1efeb53fb5c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='machineCategory']</value>
      <webElementGuid>43fb728c-e396-484c-9a42-cdd69a882ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>85fbf38e-bdae-4d94-975c-a4d637998c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8193b6c8-2efa-4360-bacd-23988beedb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'machineCategory' and @type = 'text' and @name = 'machineCategory' and @placeholder = 'Enter category name']</value>
      <webElementGuid>b526f9a3-c568-410c-8fba-c3ee6fdaeec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
