<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancel</name>
   <tag></tag>
   <elementGuidId>25eed2d8-4ac1-4606-81dd-7810f76c14aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.closeBtn__F1RCp > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;unifiller logo Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fa92f6f-8656-46b6-8aae-b2ca38d1fdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>85503795-82cf-46c4-98e9-ddff80c53662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;popupWrapper__SNDdr&quot;]/div[@class=&quot;popup__lNAxw&quot;]/div[@class=&quot;popupHeader__X6hr2&quot;]/button[@class=&quot;closeBtn__F1RCp&quot;]/span[1]</value>
      <webElementGuid>e129b09d-b2b8-45e8-97dc-4d97a1d1f524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/button/span</value>
      <webElementGuid>20ac8465-c15c-44c1-8faf-ebfc40bc0471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hashtags'])[1]/following::span[1]</value>
      <webElementGuid>ed496eca-8a67-42e4-8da8-33d68f2e3b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::span[1]</value>
      <webElementGuid>9e74dd25-11d3-4bc7-a2a9-16281cfa4d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Machine'])[1]/preceding::span[1]</value>
      <webElementGuid>3215716c-90bf-440e-9542-230d6a1cb24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>f15b2ecf-f893-42e4-9c86-0186bc826584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>5a636832-16d9-464c-9ead-eaa07433be19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>8f21d08f-7aeb-44c5-a1f7-3c8838583d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
