<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book_confirmation_req-book-img__gVxuc</name>
   <tag></tag>
   <elementGuidId>e9e3c801-2f62-44c4-8eb0-c2e52b511018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.confirmation_req-book-img__gVxuc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/main/section[2]/article/div/div[2]/p[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;req to book&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aef88a00-47d6-47f4-8085-5d8b9d59599a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/dashboard-img.jpg</value>
      <webElementGuid>2d774c11-72c2-4d57-93e5-00d9fc69e512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>req to book</value>
      <webElementGuid>c363a49e-340a-4e14-9c42-c66dde22cf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirmation_req-book-img__gVxuc</value>
      <webElementGuid>bc6760c4-fb04-469f-ad70-dac7ba8d2901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/section[@class=&quot;page-wrapper_page-wrapper___qdV9 dashboard_parent-dashboard-page__c_b6e&quot;]/main[@class=&quot;main-content-wrapper_main-content-wrapper__VIkiy&quot;]/section[@class=&quot;modal&quot;]/article[@class=&quot;confirmation_confirmation-wrapper__DWPfY modal-animation_modal-container__3bfC_&quot;]/div[@class=&quot;modal-animation_modal-scrollable__gwyes&quot;]/div[@class=&quot;confirmation_modal-body__cWURy modal-body_modal-body___e23Q&quot;]/p[@class=&quot;confirmation_req-book-img-container__oDUR_&quot;]/img[@class=&quot;confirmation_req-book-img__gVxuc&quot;]</value>
      <webElementGuid>0b77f08f-a266-4eac-9a3e-bda0fc45fd12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/main/section[2]/article/div/div[2]/p[2]/img</value>
      <webElementGuid>2b8b1016-1cef-4e24-b92e-38903e96b2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book'])[1]/following::img[1]</value>
      <webElementGuid>d38d8a5d-50a1-4fd8-91fc-9dc8b5669954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/following::img[1]</value>
      <webElementGuid>fc17ddb8-3d0d-47c0-b45e-722ff0c07f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::img[1]</value>
      <webElementGuid>dc96c170-853a-482f-901f-e679846e09a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='req to book']</value>
      <webElementGuid>0810059e-172a-4aca-b095-438e43d0598e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/img</value>
      <webElementGuid>b9b3bb36-07ba-44bb-aec2-77bd90895718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/dashboard-img.jpg' and @alt = 'req to book']</value>
      <webElementGuid>2561cf9d-10ba-4257-a8ad-b9e73b04e2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
