<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_searchAddress</name>
   <tag></tag>
   <elementGuidId>6fedabae-5284-42f7-af1f-df572f905a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchAddress&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dff60325-f5ff-48ca-b4ed-a3c33451ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field_input-field__q0AGg google-address-input_input-field__gjCFA</value>
      <webElementGuid>bf23b402-7438-4d90-8ce5-f92d816538f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchAddress</value>
      <webElementGuid>b6f91fb7-3cf7-4f40-a1c8-bc68c4ecbb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>66fd8882-c0f6-4982-b41c-320fb9fe2cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off_XXXXX</value>
      <webElementGuid>0069e43c-2868-47af-9ce1-4db2bed11e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/section[@class=&quot;page-wrapper_page-wrapper___qdV9 dashboard_parent-dashboard-page__c_b6e&quot;]/main[@class=&quot;main-content-wrapper_main-content-wrapper__VIkiy&quot;]/section[@class=&quot;dashboard_dashboard-section__Jc7HO&quot;]/div[@class=&quot;dashboard_dashboard-find-upcoming-wrapper__YZkHD&quot;]/section[@class=&quot;find-care-taker_find-care__dT4Xh&quot;]/div[@class=&quot;find-care-taker_find-care-card__M2tXE&quot;]/div[@class=&quot;find-care-taker_care-taker-container__Qtekp&quot;]/div[@class=&quot;care-taker-filters_care-taker-filters-wrapper__LNIgG&quot;]/div[@class=&quot;care-taker-filters_google-address-element__2e_rK input-field_form-group__ObEo8 google-address-input_google-input-wrapper__6BKOF&quot;]/div[@class=&quot;input-field_input-field-wrapper__I52sb google-address-input_input-field-wrapper__JqLG6&quot;]/input[@class=&quot;input-field_input-field__q0AGg google-address-input_input-field__gjCFA&quot;]</value>
      <webElementGuid>4f937f68-b5ae-4d6b-afb1-d1026a94d2d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchAddress']</value>
      <webElementGuid>0486b1b3-6caf-4aff-90b6-ec8a4df26687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/main/section/div[2]/section/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>5fd45140-91db-4056-bb0c-f79d0a29aa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::input[1]</value>
      <webElementGuid>758db285-3f65-4377-9953-3a4b70b4c7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child Jnr Two'])[1]/following::input[3]</value>
      <webElementGuid>676c4c1a-bb37-410b-91b5-3e1ef9628bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::input[1]</value>
      <webElementGuid>dcabcad8-44d7-4541-b801-91d138d3368f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move left'])[1]/preceding::input[1]</value>
      <webElementGuid>74d84d06-b657-4d6d-bc60-1ef85c5cfbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2723ee69-6da4-4e16-9cb0-5b1e8b7f2483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'searchAddress' and @placeholder = 'Address']</value>
      <webElementGuid>9328c764-02fa-472d-ad02-be615e396065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
