<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_London</name>
   <tag></tag>
   <elementGuidId>dffb9d43-f501-4ed7-9216-b1e3a533fdd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.google-address-input_predictions__16t89</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/main/section/div[2]/section/div[2]/div/div/div[3]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;London&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8c07946e-ed41-4314-ab84-e51766944e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>821ad0d4-bcc0-4ead-a906-ed12125c988b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-address-input_predictions__16t89</value>
      <webElementGuid>bcc1a862-8761-439a-ac2d-00bec91fe115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>London</value>
      <webElementGuid>e5322d2c-d75d-4680-b242-06e293e28851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/section[@class=&quot;page-wrapper_page-wrapper___qdV9 dashboard_parent-dashboard-page__c_b6e&quot;]/main[@class=&quot;main-content-wrapper_main-content-wrapper__VIkiy&quot;]/section[@class=&quot;dashboard_dashboard-section__Jc7HO&quot;]/div[@class=&quot;dashboard_dashboard-find-upcoming-wrapper__YZkHD&quot;]/section[@class=&quot;find-care-taker_find-care__dT4Xh&quot;]/div[@class=&quot;find-care-taker_find-care-card__M2tXE&quot;]/div[@class=&quot;find-care-taker_care-taker-container__Qtekp&quot;]/div[@class=&quot;care-taker-filters_care-taker-filters-wrapper__LNIgG&quot;]/div[@class=&quot;care-taker-filters_google-address-element__2e_rK input-field_form-group__ObEo8 google-address-input_google-input-wrapper__6BKOF&quot;]/ul[@class=&quot;google-address-input_predictions-list__jByDD&quot;]/li[@class=&quot;google-address-input_predictions__16t89&quot;]</value>
      <webElementGuid>7c48c93a-8c3f-40c3-9264-847b62575e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/main/section/div[2]/section/div[2]/div/div/div[3]/ul/li</value>
      <webElementGuid>09aa004b-6645-4329-ae19-23e9ab002d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::li[1]</value>
      <webElementGuid>3dc7a303-cb3c-441e-8ae5-d864b7d0915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child Jnr Two'])[1]/following::li[1]</value>
      <webElementGuid>cea63a29-ee71-43a6-b0c5-45a208f99f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='London Luton Airport (LTN)'])[1]/preceding::li[1]</value>
      <webElementGuid>50f0f0f0-ab8a-4d58-9dcd-e9f0e8a46978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='London Bridge'])[1]/preceding::li[2]</value>
      <webElementGuid>9a575d4e-c37b-4273-ab51-10422c4c3bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>610b6908-325a-4de9-ad49-233088bf286d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'London' or . = 'London')]</value>
      <webElementGuid>abe05e53-432d-42e2-89b6-a0de07c631e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
