<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Archive_1</name>
   <tag></tag>
   <elementGuidId>45fbb7b0-3f82-4639-83b2-ba01aebaceab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn__Yg5tI.btn-default__apt_1.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Archive&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1812636-f9e0-4c79-9266-8900b3781f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e0b19f3-6805-41d3-af3a-28167888fc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__Yg5tI btn-default__apt_1 undefined</value>
      <webElementGuid>67062379-7211-4239-92b7-2dc90916ab84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Archive </value>
      <webElementGuid>6e6e7f36-1023-4686-8e89-d254160dddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;warningContentWrapper__jMQXB&quot;]/div[@class=&quot;warningContent__X5msa&quot;]/div[@class=&quot;deleteWarningWrapper__r1VQa&quot;]/div[@class=&quot;footerSection__GW_UT&quot;]/div[@class=&quot;footerButtonSection__y2HC9&quot;]/div[@class=&quot;wrapper-content-no-top__n1ude small-gap__LOY63&quot;]/button[@class=&quot;btn__Yg5tI btn-default__apt_1 undefined&quot;]</value>
      <webElementGuid>2b7e1a0a-9529-4a99-af2d-7e6b6d0a031f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>3d843d13-eaff-40bd-9a97-330b7e06939a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div/div/button</value>
      <webElementGuid>d0bd400e-1bab-47a5-811f-a1253f97f4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>d7be3ef4-44a8-4356-b678-e890edaa559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you would like to archive this machine?'])[1]/following::button[2]</value>
      <webElementGuid>11748563-e4d0-43fa-be84-9ac8fb5e92ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/button</value>
      <webElementGuid>09c10d8f-c6e0-4d04-8b1c-ca004f84c523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Archive ' or . = 'Archive ')]</value>
      <webElementGuid>0b57731e-f951-4733-b7b8-2cc48e73aa48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
