<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New Subcat  V234MultiStation 2023  New Cat</name>
   <tag></tag>
   <elementGuidId>f2522dec-407f-48c3-befe-1230a928f3f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.innerWrapper__nKtim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollableDiv']/div/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^New Subcat • V234MultiStation 2023 • New Cat$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>576f26e5-f9c3-4502-9189-2092120fd188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>innerWrapper__nKtim</value>
      <webElementGuid>6b34f577-4502-4dba-b43a-895b1172509b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Subcat • V234MultiStation 2023 • New Cat</value>
      <webElementGuid>3a932ef9-12c1-4869-b0cf-683cfb46328d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableDiv&quot;)/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component cardsContainer__umG0f&quot;]/span[@class=&quot;card__UE6m0&quot;]/div[@class=&quot;innerWrapper__nKtim&quot;]</value>
      <webElementGuid>20d0ef95-dfb6-4cf6-97ef-1524ce8c6d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableDiv']/div/div/span/div</value>
      <webElementGuid>b026bd51-600b-410b-ac98-792e2ec71fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version Decremental'])[1]/following::div[6]</value>
      <webElementGuid>e3fbcc27-8a61-48d8-a542-899360c448f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filters'])[1]/following::div[14]</value>
      <webElementGuid>76f51c98-e334-4b99-989d-31ed18fc720d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Subcat • V123'])[1]/preceding::div[6]</value>
      <webElementGuid>bc18db35-228c-4bf3-87ca-97d15e5af76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>f627d065-a9e7-449d-b2c1-caa7446237d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New Subcat • V234MultiStation 2023 • New Cat' or . = 'New Subcat • V234MultiStation 2023 • New Cat')]</value>
      <webElementGuid>5f3cecaf-eaec-472e-a087-4ac11a22e798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
