<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select category_css-15lsz6c-indicatorContainer</name>
   <tag></tag>
   <elementGuidId>a1e48e77-4204-4e68-abb3-32aa71a24eb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-15lsz6c-indicatorContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='events[0].maintenanceCategory']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-15lsz6c-indicatorContainer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e44d781-b355-45a5-86d3-0004b50b45a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-15lsz6c-indicatorContainer</value>
      <webElementGuid>cdfbb413-9f86-4966-bca9-82480c36e3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b08249d0-28bc-4820-b9f8-307671ee6c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;events[0].maintenanceCategory&quot;)/div[@class=&quot;css-18y7qp5-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-15lsz6c-indicatorContainer&quot;]</value>
      <webElementGuid>11fa369d-ee4d-48fa-8b7a-b969d543ba0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='events[0].maintenanceCategory']/div/div[2]/div</value>
      <webElementGuid>9e15852b-5e09-400c-a4aa-f3c73825362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select category'])[1]/following::div[3]</value>
      <webElementGuid>4dcbf13c-d177-4734-8ae6-0210eb067534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[8]</value>
      <webElementGuid>7508b293-8f1f-44dc-a9c6-fcfb628b576b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a category.'])[1]/preceding::div[1]</value>
      <webElementGuid>1a271e71-0bee-4df2-b2ea-c812f03d9d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>dc1e7e20-17a3-4cb2-b196-810e9ff48cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
