<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reset Filters</name>
   <tag></tag>
   <elementGuidId>59115e22-037c-4223-ba42-65662d9084c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.resetFiltersSpan__IY20q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Reset Filters&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14a27bb4-29f4-4cac-94c5-aba87aea3a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resetFiltersSpan__IY20q</value>
      <webElementGuid>404c60c9-6db1-477e-b7e6-a76aad17b5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset Filters</value>
      <webElementGuid>c8643f17-2cf7-4f21-b22c-1ad1967aadc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;resultsListHeader__KK1hJ&quot;]/div[@class=&quot;dropdownContainer__Q0UJX&quot;]/div[@class=&quot;resetFilters__v7SBn&quot;]/span[@class=&quot;resetFiltersSpan__IY20q&quot;]</value>
      <webElementGuid>f3f270b8-eb87-455b-bd24-3c68d8d4e06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div[4]/span</value>
      <webElementGuid>7b6f4056-dc38-44b8-8383-220fb5645e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New sub cat 2023'])[1]/following::span[1]</value>
      <webElementGuid>75097f55-0735-4df8-9c15-2543a9b85852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start searching or filtering to find machines.'])[1]/preceding::span[1]</value>
      <webElementGuid>c7ef90b3-a7bf-4bdb-b0ac-aa577502fd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset Filters']/parent::*</value>
      <webElementGuid>e38e38f9-e7b4-4692-99f2-936aa2c938b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>7f26369c-5baf-417e-9b2c-efb7603e9535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reset Filters' or . = 'Reset Filters')]</value>
      <webElementGuid>4246e360-f11b-4aeb-8f27-bb9d7b38a4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
