<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select a location_css-19bb58m</name>
   <tag></tag>
   <elementGuidId>4db9b44d-3431-4444-8fee-dec0326faaf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-18y7qp5-control > div.css-hlgwow > div.css-19bb58m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='location-dropdown']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-18y7qp5-control > .css-hlgwow > .css-19bb58m</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b170f15-2384-441d-9e73-a721073c6c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-19bb58m</value>
      <webElementGuid>5bf47602-408c-488c-b2d1-53197e1383bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-dropdown&quot;)/div[@class=&quot;css-18y7qp5-control&quot;]/div[@class=&quot;css-hlgwow&quot;]/div[@class=&quot;css-19bb58m&quot;]</value>
      <webElementGuid>ee1757ba-6b27-4811-9929-b92bfdc9e825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location-dropdown']/div/div/div[2]</value>
      <webElementGuid>c99ef3b4-bc46-4a16-9bdc-134957b35ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a location'])[1]/following::div[1]</value>
      <webElementGuid>a461398d-6f42-4f88-a783-a1175ab398e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a role'])[1]/preceding::div[3]</value>
      <webElementGuid>1733ee88-0553-4f9c-9653-c1c2f1c89479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>d7d9970b-0de1-4e2e-ba5f-fada20471e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
