<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select a department</name>
   <tag></tag>
   <elementGuidId>98a32d9f-4b9f-4fdb-a218-7463c1b4869a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-hlgwow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='department-dropdown']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Select a department$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2f21677-9c2a-4a05-8741-0ae2070fcbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-hlgwow</value>
      <webElementGuid>4ccea473-739f-4f7a-8d50-f3654b28c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a department</value>
      <webElementGuid>8984dd72-33f8-429a-9f6c-ceb82bc854ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department-dropdown&quot;)/div[@class=&quot;css-18y7qp5-control&quot;]/div[@class=&quot;css-hlgwow&quot;]</value>
      <webElementGuid>195e81ae-0e38-490c-9869-ca8a7d7b14bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='department-dropdown']/div/div</value>
      <webElementGuid>097d86e4-17f7-4792-a735-97a130c1dced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who are you looking for:'])[1]/following::div[12]</value>
      <webElementGuid>1a0ace47-d67a-440e-8a65-a9c3e6792a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>540f276a-4a37-4b42-b8f8-e5c53489c9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select a department' or . = 'Select a department')]</value>
      <webElementGuid>04af3928-3df1-45e7-aef8-a4fbef28ca30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
