<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who are you looking for_machine-search</name>
   <tag></tag>
   <elementGuidId>d16cb862-23ba-4915-8040-01a856406a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#machine-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='machine-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cda3aa10-8ee2-4d10-9f4b-9c9b9a36d4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>fc595690-0e1c-4007-8634-fabc8b06ab45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3370fe20-83c9-4d77-9fa5-02b27df5dacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>9acc9c19-a040-4378-a894-ee5724b94984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>afb2c9b8-fdf8-48a1-9bc8-4487984b6b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95ab0892-0e6b-4cb8-b985-52892cd814c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;machine-search&quot;)</value>
      <webElementGuid>8f211438-5d2f-4456-9803-e09a5f9a0a27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='machine-search']</value>
      <webElementGuid>15d05ac4-10d6-423c-ab00-58c14b54e17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>7e84c4a3-70ba-4eca-9360-589c27d5cdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5573136f-8960-4f9f-9288-b624b4d87500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'machine-search' and @type = 'text' and @name = 'machine-search' and @placeholder = 'Search']</value>
      <webElementGuid>ff8e8462-4b1f-404b-a117-df9e6f1270ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
