<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Restore_1</name>
   <tag></tag>
   <elementGuidId>1845518d-ec8b-4dac-9ef3-1d8c2de43e40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn__Yg5tI.btn-default__apt_1.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Restore&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f423620-b92d-4ecd-b16c-b2b518771f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4a17909f-f486-49a0-878b-3631eb002ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__Yg5tI btn-default__apt_1 undefined</value>
      <webElementGuid>8c24abcd-c97f-4f54-b36e-b41d6bd5d3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restore </value>
      <webElementGuid>fb603ab4-f202-4539-8a50-f4e7ae5fa28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;warningContentWrapper__jMQXB&quot;]/div[@class=&quot;warningContent__X5msa&quot;]/div[@class=&quot;deleteWarningWrapper__r1VQa&quot;]/div[@class=&quot;footerSection__GW_UT&quot;]/div[@class=&quot;footerButtonSection__y2HC9&quot;]/div[@class=&quot;wrapper-content-no-top__n1ude small-gap__LOY63&quot;]/button[@class=&quot;btn__Yg5tI btn-default__apt_1 undefined&quot;]</value>
      <webElementGuid>3e8f71b8-35e5-4f61-a141-1d745d0c36ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>bb4cbb28-e00c-449c-84ef-fcd4cc7e5ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div/div/button</value>
      <webElementGuid>53891e92-4d91-417b-886d-87299fa2dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>75c1ee68-0e25-4b01-a9dc-4e0acb9357e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to restore this machine?'])[1]/following::button[2]</value>
      <webElementGuid>ab6630cc-9cc1-4ccb-b544-2c59814885da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/button</value>
      <webElementGuid>77e1e571-9c65-4550-9fa0-a2de41155daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Restore ' or . = 'Restore ')]</value>
      <webElementGuid>ff801662-13eb-4055-90f5-a9b9c2095fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
