<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_machines81 Archived Machine Versions</name>
   <tag></tag>
   <elementGuidId>3aa6bca4-3384-4c62-8fc2-dfa572dbde04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.innerWrapper__nKtim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;archives-machines-icon machines 81 Archived Machine Versions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22209367-9a34-4726-b30e-74296ee5ec13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>innerWrapper__nKtim</value>
      <webElementGuid>5f833ad3-5ff3-4d76-82b1-bee90afc0d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>machines81 Archived Machine Versions</value>
      <webElementGuid>8f7bfd2f-0c27-4580-b5e6-bfa109062cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;cardsContainer__Bkidd&quot;]/a[@class=&quot;card__bB1NV&quot;]/div[@class=&quot;innerWrapper__nKtim&quot;]</value>
      <webElementGuid>75331240-7f32-4465-b178-34eb1b4786c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/a/div</value>
      <webElementGuid>7299fa93-00ec-4bb8-93cf-1b571a3b8ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archives'])[2]/following::div[2]</value>
      <webElementGuid>29431d13-dc4e-4ad9-a911-35729318fd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[5]</value>
      <webElementGuid>4bcc6bcd-cf72-4c0c-87bf-8b522cda534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customers'])[1]/preceding::div[6]</value>
      <webElementGuid>568c4c34-2023-4d83-a73a-6bc46c5946ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>1afd7df2-6f29-437c-829c-81f466373fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'machines81 Archived Machine Versions' or . = 'machines81 Archived Machine Versions')]</value>
      <webElementGuid>5c257980-2b96-4c71-b4fb-d3dd5869a4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
