<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What are you looking for_clear-icon__i7jZ1</name>
   <tag></tag>
   <elementGuidId>2de44d67-b4c0-4531-b0fb-cdc0a76de2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.clear-icon__i7jZ1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^What are you looking for:$/ >> div >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79d4aceb-617c-4df0-b78a-0368823826fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level-up</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d56e54d-bf02-466e-8ad4-683572471964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clear-icon__i7jZ1</value>
      <webElementGuid>228b85d9-d0ee-48b4-8789-ab6218a49b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffa66f8e-27fc-463a-83b9-f5a55c65ed24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;resultsArchivedHeader__REttE&quot;]/div[@class=&quot;resultsListHeaderMiddle__rCSMu&quot;]/div[@class=&quot;resultsListSearchWrapper__HcNKW&quot;]/div[1]/div[@class=&quot;input-field__RQCOL&quot;]/div[@class=&quot;clear-icon__i7jZ1&quot;]</value>
      <webElementGuid>3ddbd3ea-68b9-4dd7-824b-da08f9b5997e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>697dbb52-5d45-4205-9157-a1e266d75e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for:'])[1]/following::div[5]</value>
      <webElementGuid>74805e03-7ba5-4755-81e8-121c6505a306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archived Customers'])[1]/following::div[6]</value>
      <webElementGuid>d8a62193-c4bf-46c7-8338-55ea7662e3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/preceding::div[1]</value>
      <webElementGuid>c0f7063e-d989-45b8-9ca8-a6df0bffb2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifiller+ ID'])[1]/preceding::div[2]</value>
      <webElementGuid>eb9b8658-b689-4506-b193-8ed7a375b41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]</value>
      <webElementGuid>9f2f2205-da89-41f1-ac33-0283afa92c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
