<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What are you looking for_machine-search</name>
   <tag></tag>
   <elementGuidId>07172f8e-ee8b-4742-9f6b-b2716ea4868b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#machine-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='machine-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f34158d-cc40-47e6-b5c4-6120ba7721a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>f2245768-6077-446a-87fd-e0bbf50a1b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b72e9cec-013c-4ab0-9613-5dc46a7a59eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>dab8a78c-391c-493a-831e-132dc4449bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f49d3b79-3ccb-4072-a20a-b3669b47b1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6bfb50a-0bbe-436d-952f-3e09db334aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;machine-search&quot;)</value>
      <webElementGuid>f4196fff-1df2-4248-91ea-e4b82ca7ba29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='machine-search']</value>
      <webElementGuid>b69abfaa-61e9-4364-a7b7-c5f39fabec92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>d85983b9-afa9-4cea-a41d-6649b65b185d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ac9c8707-d521-48d5-a7ff-d483496fa7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'machine-search' and @type = 'text' and @name = 'machine-search' and @placeholder = 'Search']</value>
      <webElementGuid>0db0bf1c-5985-4599-b6d1-dabdd1b1b8a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
