<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Privacy policy</name>
   <tag></tag>
   <elementGuidId>168f58dc-a35e-4d7e-b289-687d89cbf7f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Privacy policy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c7238ac-5160-4bb8-857f-790e441fe864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9beabbc-e941-4eab-a3b3-ce8cc3558c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>settings-wrapper_tab-links__xT6M3 button_btn__FBLjm button_primary-btn__wVvvb</value>
      <webElementGuid>daab2729-3dae-40a5-a4db-e1c9560d5400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy policy</value>
      <webElementGuid>10569be5-e74d-4497-8aa8-bde618d6662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/div[1]/section[@class=&quot;page-wrapper_page-wrapper___qdV9&quot;]/main[@class=&quot;main-content-wrapper_main-content-wrapper__VIkiy&quot;]/div[@class=&quot;settings-wrapper_header-title-wrapper__ySjae&quot;]/div[@class=&quot;settings-wrapper_tabs-wrapper__I_sdG&quot;]/ul[@class=&quot;settings-wrapper_tabs__pQzfB&quot;]/li[@class=&quot;settings-wrapper_link-wrapper__yST0S&quot;]/a[1]/button[@class=&quot;settings-wrapper_tab-links__xT6M3 button_btn__FBLjm button_primary-btn__wVvvb&quot;]</value>
      <webElementGuid>7c1bc9c2-392e-4cda-baf2-1604c9933e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>309a1211-fb63-4561-86ea-d2ca8676e3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/section/main/div/div/ul/li[6]/a/button</value>
      <webElementGuid>e42778f4-1606-4ee0-aa2e-9605e7cb887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; conditions'])[1]/following::button[1]</value>
      <webElementGuid>a0033047-384f-4c36-a33d-c77b97319dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank details'])[1]/following::button[2]</value>
      <webElementGuid>907732a4-3d0b-48d0-beed-525ac708b6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WELCOME TO DAYCARE SOS'])[1]/preceding::button[1]</value>
      <webElementGuid>b59af9cc-3535-4630-ad2d-76763552ccce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.daycaresos.com'])[1]/preceding::button[1]</value>
      <webElementGuid>06df8533-f185-4489-9a91-1e02bea77256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/button</value>
      <webElementGuid>15c26dc7-2d42-4d67-a96e-8739d27ad885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Privacy policy' or . = 'Privacy policy')]</value>
      <webElementGuid>a1aa2743-a681-4446-a95e-8d662ae23eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
