<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Date of booking</name>
   <tag></tag>
   <elementGuidId>14d4c3e6-b13a-4bfc-9be1-f211931ad13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.general-table_table-head-title__NaQSG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/main/div/div[2]/div/table/thead/tr/th/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>thead >> internal:text=&quot;Date of booking&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59d12461-2c43-4430-b648-d6a3c94e8205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>general-table_table-head-title__NaQSG</value>
      <webElementGuid>7b6b92da-9247-474c-af03-c618cf440855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date of booking</value>
      <webElementGuid>e4bdafe6-b0e2-4af1-8f8c-e31f911089fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/main[1]/section[@class=&quot;page-wrapper_page-wrapper___qdV9&quot;]/main[@class=&quot;main-content-wrapper_main-content-wrapper__VIkiy&quot;]/div[@class=&quot;parent-bookings_parent-bookings-flow-wrapper__zhZZz&quot;]/div[@class=&quot;past-bookings_past-bookings-wrapper__chYqU&quot;]/div[@class=&quot;general-table_table-wrapper__3m1sV past-bookings_table-wrapper__6kE4m&quot;]/table[@class=&quot;general-table_table__z5NKs past-bookings_table__ngzFG&quot;]/thead[@class=&quot;general-table_table-head__j_dx8&quot;]/tr[@class=&quot;general-table_table-head-row__Kz6Zu&quot;]/th[1]/div[@class=&quot;general-table_table-head-row-content__MSfIO&quot;]/div[@class=&quot;general-table_table-head-title__NaQSG&quot;]</value>
      <webElementGuid>6056ed5a-c6a7-4139-9f8d-f2e82b8413cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/main/div/div[2]/div/table/thead/tr/th/div/div</value>
      <webElementGuid>ff849b20-8bde-4f5e-b845-8f2b78a02cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by'])[1]/following::div[8]</value>
      <webElementGuid>d5a50c24-371a-4051-9975-992576b172b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Past Bookings'])[1]/following::div[13]</value>
      <webElementGuid>ce33cab0-dedf-41c7-bba3-a45cbda93c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking ID'])[1]/preceding::div[3]</value>
      <webElementGuid>29e0da22-400a-47f5-8503-d8eb26f5b600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[5]</value>
      <webElementGuid>e7b351d6-4385-47bd-99ed-a49c308bcc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/div</value>
      <webElementGuid>dd5f2630-f096-4e83-a93b-8572fd02d1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Date of booking' or . = 'Date of booking')]</value>
      <webElementGuid>3a1e0fd8-4f86-42a9-80b6-bba881c076cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
