<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customers</name>
   <tag></tag>
   <elementGuidId>added26b-3f51-4842-b10b-71c55b65559a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.inactive__C18L4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/nav/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Customers Customers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68fa97ed-b980-4967-b2e5-4a1b90b5adb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exact</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7c4d79a-88d2-440c-91c5-fc9828ebdbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactive__C18L4</value>
      <webElementGuid>e6bf3ecc-6236-4bf2-83f1-409c63bee6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customers</value>
      <webElementGuid>15900546-575d-4a93-9f18-9c5bdc271a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customers</value>
      <webElementGuid>2202579f-f296-465c-aebc-c2c0e830a18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sideBarWrapper__FI32v&quot;]/nav[@class=&quot;navbar__MERVD&quot;]/ul[1]/li[2]/a[@class=&quot;inactive__C18L4&quot;]</value>
      <webElementGuid>d2a6e2c7-ea84-4ff8-a264-e60de198ef7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/nav/ul/li[2]/a</value>
      <webElementGuid>eb77b40f-82f7-4aa0-b9dd-b760248e68d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Machines'])[1]/following::a[1]</value>
      <webElementGuid>37e1e3fa-f848-42db-baeb-98282ef55d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/preceding::a[1]</value>
      <webElementGuid>327fe31c-34a1-4733-a9f9-e58b3d91ab83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customers')]</value>
      <webElementGuid>692dd317-d190-41f6-b24f-8e2c24ed236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>7cceac14-c2d3-4304-983c-8f9ff9ea93b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customers' and (text() = 'Customers' or . = 'Customers')]</value>
      <webElementGuid>95b58320-69d0-4b3f-92e6-dfd9bcf64615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
