<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Customer</name>
   <tag></tag>
   <elementGuidId>328f7313-fb4a-40c4-a3c0-e4395520d330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='24']/div/div[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Customer.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37cfc8bc-fe5c-4d1e-b1b0-086678e487eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qa.cms.unifiller.studiographene.xyz/archives/customers/details/1bb3323e-a086-485d-a273-7682ca524c56</value>
      <webElementGuid>91281aa1-abd9-4be1-bde7-07fb44051232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4bc608d3-8a8a-402f-aeb0-6e61cb1bd26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>0daa6d22-b2a5-4362-995e-8432ff16b1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Customer.</value>
      <webElementGuid>48f9118c-e545-480e-b73d-a7e52bab7fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;24&quot;)/div[@class=&quot;Toastify__toast-body toast-body&quot;]/div[2]/p[1]/a[1]</value>
      <webElementGuid>99a27716-2ffd-48f1-b95c-d1d2bf0152f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='24']/div/div[2]/p/a</value>
      <webElementGuid>c4a2425d-ae4b-47ba-934c-26eae049fd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Customer.')]</value>
      <webElementGuid>8bdf2d59-a9e3-41c4-a8f6-c13829136b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This customer has been successfully archived.'])[1]/following::a[1]</value>
      <webElementGuid>f9d835ca-a8da-4af6-948b-14b3248fb5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success!'])[1]/following::a[1]</value>
      <webElementGuid>75611fdf-e1a5-4722-a8b2-ca10e9e3359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Machines'])[1]/preceding::a[1]</value>
      <webElementGuid>bf6f27cc-dcc0-46d9-be20-24714ec67bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[1]/preceding::a[2]</value>
      <webElementGuid>facea957-83ac-4755-a425-b17b805c51bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Customer.']/parent::*</value>
      <webElementGuid>00e3b3fd-3856-4bbf-b025-85d35abb64d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qa.cms.unifiller.studiographene.xyz/archives/customers/details/1bb3323e-a086-485d-a273-7682ca524c56')]</value>
      <webElementGuid>2387be20-2665-44a3-9d41-20aa98fc8384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e359f849-6bd6-44c2-bebb-ffd53d218897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://qa.cms.unifiller.studiographene.xyz/archives/customers/details/1bb3323e-a086-485d-a273-7682ca524c56' and (text() = 'View Customer.' or . = 'View Customer.')]</value>
      <webElementGuid>12437982-0c72-4003-b46b-360268d5efef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
