<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add New</name>
   <tag></tag>
   <elementGuidId>125a0fcd-a058-4b26-afb7-7bf5914b8f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn__Yg5tI.btn-default-medium___Ld49.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;add-new-item Add New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df0a0ea7-e641-4da6-b8c1-389e5c43002e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>429b9708-d4e7-43b1-b34b-e4ea4f470025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__Yg5tI btn-default-medium___Ld49 undefined</value>
      <webElementGuid>9ded659a-eb08-48ce-bb67-d422399fcebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New </value>
      <webElementGuid>b913d623-dc9b-4605-afb6-aeff7946e9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;resultsListHeader__KK1hJ&quot;]/div[@class=&quot;resultsListHeaderTop__DsiuU resultsListHeaderTopLine__tNaP5&quot;]/button[@class=&quot;btn__Yg5tI btn-default-medium___Ld49 undefined&quot;]</value>
      <webElementGuid>156f0a19-473b-445f-b99f-4035fe82aa85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>c0e40f4f-7405-4721-a173-b5063216e784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/button</value>
      <webElementGuid>98c4fb40-103d-4eb7-bad2-7c6562006f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[2]/following::button[1]</value>
      <webElementGuid>67a8e1b1-2b2c-4bf2-ad9c-ef3d7cfa151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::button[1]</value>
      <webElementGuid>1ba6ab6a-75fe-4050-9dee-47eeae63b298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for:'])[1]/preceding::button[1]</value>
      <webElementGuid>7ad0c85d-8da0-4330-8288-8c30b8ac527d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>baead0ac-df03-46b7-b0c6-b940c8470a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add New ' or . = 'Add New ')]</value>
      <webElementGuid>c2e51264-cd09-477f-ba89-a74782038307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
