<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm and continue</name>
   <tag></tag>
   <elementGuidId>021fc5c7-76cb-452c-8ee2-6ff97c923ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn__Yg5tI.btn-default__apt_1.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm and continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00968fee-4c8f-4c4c-8279-4df915d24937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>16dbf721-08e4-4982-95aa-0a3b268dc2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__Yg5tI btn-default__apt_1 undefined</value>
      <webElementGuid>263ea32a-35ef-43b1-b5a2-7ab7b33d22bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm and continue </value>
      <webElementGuid>80eecd9a-40c1-4213-a771-3e82c90cf1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;addWrapper__fL80K&quot;]/form[@class=&quot;tcdWrapper__P9NRs&quot;]/div[@class=&quot;bottomSection__UnyzP&quot;]/div[@class=&quot;footerSection__Z5n5Z&quot;]/button[@class=&quot;btn__Yg5tI btn-default__apt_1 undefined&quot;]</value>
      <webElementGuid>821a4912-a847-44aa-a9a8-b09efcefbb48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>11ca3244-c9c6-4095-9e1b-5ad85ca647b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[2]/div/button[2]</value>
      <webElementGuid>e0f2c074-36f2-477a-9462-c20bc9218e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>9b9f2007-0d67-4495-9c64-96b30d6f4ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@unifiller.plus'])[1]/following::button[2]</value>
      <webElementGuid>9fdea8da-107b-4655-aafd-6a7d6798d280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm and continue']/parent::*</value>
      <webElementGuid>3e742d72-db51-484a-bc12-eac6a6095887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>75bbfeb6-32d7-43dc-9d5e-ecf538f8522f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Confirm and continue ' or . = 'Confirm and continue ')]</value>
      <webElementGuid>eb821ae6-5e84-4c9d-bb54-afff4244fc0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
