<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What are you looking for_clear-icon__i7jZ1</name>
   <tag></tag>
   <elementGuidId>67272bf7-0c54-4a14-9cfb-b420dad70706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.clear-icon__i7jZ1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^What are you looking for:$/ >> div >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04ff05e0-1e29-43b8-86f8-4cd50f18dba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level-up</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77a79a55-988f-4508-8f5a-d69a18f745fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clear-icon__i7jZ1</value>
      <webElementGuid>4289f6b7-d562-471b-b21c-07930cb3fde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73cfc6f0-2f23-4f02-a253-fc6fc1c3d1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;resultsListHeader__KK1hJ&quot;]/div[@class=&quot;resultsListHeaderMiddle__rCSMu&quot;]/div[@class=&quot;resultsListSearchWrapper__HcNKW&quot;]/div[1]/div[@class=&quot;input-field__RQCOL&quot;]/div[@class=&quot;clear-icon__i7jZ1&quot;]</value>
      <webElementGuid>e99fdeda-12a0-462c-85a3-46b02cbddd2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>79ce2fd5-5cc5-46db-bdfb-4da0e145b8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for:'])[1]/following::div[5]</value>
      <webElementGuid>76c4aaf9-39ec-4b35-b605-6cc3ef6c2725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[1]/following::div[6]</value>
      <webElementGuid>56e48d72-30f4-4561-9c25-f3356df031dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a subscription'])[1]/preceding::div[1]</value>
      <webElementGuid>acabf5f2-ba92-4172-9d5a-02467f8eb47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]</value>
      <webElementGuid>89adfe05-1c1c-4a06-a4b6-b31370e11013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
