<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select a subscription</name>
   <tag></tag>
   <elementGuidId>f15d5af7-c1c7-41a7-bc56-1ffd78ec6e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-hlgwow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tcaSubscription-dropdown']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Select a subscription$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f690fb98-5a25-47bf-b6ba-8dc22a230e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-hlgwow</value>
      <webElementGuid>8d22db6b-5506-4f3d-8b7d-a40c81e2f1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a subscription</value>
      <webElementGuid>fb7a7c6b-84b9-480d-96d1-212a3e3b6da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcaSubscription-dropdown&quot;)/div[@class=&quot;css-18y7qp5-control&quot;]/div[@class=&quot;css-hlgwow&quot;]</value>
      <webElementGuid>9f2fbfd5-6653-4cbc-8e36-6b2c838aca67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tcaSubscription-dropdown']/div/div</value>
      <webElementGuid>b139e1d3-e52b-42d0-b4f0-b20eccbca268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for:'])[1]/following::div[12]</value>
      <webElementGuid>59d628f7-0a04-4c46-a894-a48d9c23de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>e3e1c799-545b-4f02-a079-4de46527f3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select a subscription' or . = 'Select a subscription')]</value>
      <webElementGuid>06ae9ef4-5056-4f54-8f10-d96ea6fb287a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
