<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Full Serial Number_input-field__RQCOL</name>
   <tag></tag>
   <elementGuidId>d04e2b7f-4fa1-4769-b69d-99e742f45236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-field__RQCOL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.input-field__RQCOL</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37e6112e-fee8-4a7a-a724-b5f766230d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field__RQCOL</value>
      <webElementGuid>7e8d606c-8e74-453a-b8c2-78585a82a739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;addWrapper__fL80K&quot;]/form[@class=&quot;tcdWrapper__P9NRs&quot;]/div[@class=&quot;topSection__FeE6f&quot;]/div[@class=&quot;tcdSection__ymgFw&quot;]/div[3]/div[@class=&quot;input-field__RQCOL&quot;]</value>
      <webElementGuid>0fd7ea91-7303-4149-bd6d-9286da8416b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div/div[3]/div</value>
      <webElementGuid>6188ca91-4f98-472b-a0ab-a26ec4217f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Serial Number'])[1]/following::div[2]</value>
      <webElementGuid>1de9dbd4-2294-45fa-82de-47013be0d4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SERIAL NUMBER'])[1]/following::div[3]</value>
      <webElementGuid>7622cfb8-b251-4f4e-9992-5b83d44a4a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[3]</value>
      <webElementGuid>3f7dcd1d-45ff-47b6-9469-8ff0b18be32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm and continue'])[1]/preceding::div[3]</value>
      <webElementGuid>781c540b-4019-4688-89f2-720d66f62c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>3f5d4f54-932b-4d84-9540-d0ca81675e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
