<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What are you looking for_machine-search</name>
   <tag></tag>
   <elementGuidId>68d9bd96-16c2-46dd-980d-5d5275ac63ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#machine-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='machine-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b987fe56-437f-40f0-a062-f653e4028647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>2eb2a20a-9a84-4385-8fd3-3745f605ee08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8db3f48-4087-4e94-ab23-0eacf5fd2806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>machine-search</value>
      <webElementGuid>06c7ebe3-0340-42d4-b643-f70db64e4766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>71895cc4-158a-4028-8631-4ce967214dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ffb9813-dcdd-4942-9139-d99693c4b519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;machine-search&quot;)</value>
      <webElementGuid>e8ef7bdd-8740-439e-b971-fa38cffc2976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='machine-search']</value>
      <webElementGuid>60e09e2c-872c-4946-bd7c-3064dc8810a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>37b7595b-1631-4f03-922e-baf0f61dc49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>237a0f31-2ceb-4f2d-a767-9097b45534a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'machine-search' and @type = 'text' and @name = 'machine-search' and @placeholder = 'Search']</value>
      <webElementGuid>a82b11c3-bd53-4af3-ae5c-96ed9677eaee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
