<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resend Invitation_tableRowImage__pXJ5Z</name>
   <tag></tag>
   <elementGuidId>c27bc724-717e-4f6b-a326-253e55319d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tableRowImage__pXJ5Z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollableDiv']/div/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;error-logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>749fe5f2-7ee0-4f9d-95aa-ccd17a6eaaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tableRowImage__pXJ5Z</value>
      <webElementGuid>89cab207-dbc3-4559-9279-284ac20e6f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableDiv&quot;)/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;tableRow__muHN_&quot;]/div[@class=&quot;tableCell-extra-large___hlBS imagePlusName__fyi_H img-square__gUoFo row-active__UoGbJ&quot;]/a[@class=&quot;detailsLink__yDNIO&quot;]/span[@class=&quot;tableRowImage__pXJ5Z&quot;]</value>
      <webElementGuid>e5c974da-5f9a-427b-84a2-2dfdca66cd8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableDiv']/div/div/div/div/a/span</value>
      <webElementGuid>790a2c24-ff21-4ff9-9f8e-674965d9a341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend Invitation'])[1]/following::span[1]</value>
      <webElementGuid>109bb384-eb3d-4839-bfc2-a0bc3bcfbe9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[3]</value>
      <webElementGuid>9dbc0986-7d22-404e-b19a-4e0df211fb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifiller DEMO1'])[1]/preceding::span[1]</value>
      <webElementGuid>e4f2f151-b8ce-47e4-8e05-6c002fced259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::span[2]</value>
      <webElementGuid>04d9901c-e518-4321-9ee4-da70a40ccb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>10948475-01d9-479c-b796-f89a5f72cd83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
