<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Unifiller ID</name>
   <tag></tag>
   <elementGuidId>1a71b2a5-f079-498b-be16-0989b9487342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tcaId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tcaId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Unifiller+ ID&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8bcca21a-1e98-47c6-b4bc-16cd2b922eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerText__MMhlg</value>
      <webElementGuid>736049c6-973d-4d30-bd09-e03b861590a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tcaId</value>
      <webElementGuid>e36d266d-86bb-469f-bbd4-0225089dbf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unifiller+ ID</value>
      <webElementGuid>2ab3fa66-f517-4e98-b27f-97bb3e21f934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tcaId&quot;)</value>
      <webElementGuid>2a5a6cca-13ef-495b-a39f-bc22104431c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tcaId']</value>
      <webElementGuid>22856d58-28f3-44f9-91d0-37e6fd6e5b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div[2]/span</value>
      <webElementGuid>c4a17433-5a0d-4f70-9eeb-3cd86b589115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/following::span[2]</value>
      <webElementGuid>9231a679-4360-4b1e-bb6e-0544c630cff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Filters'])[1]/following::span[3]</value>
      <webElementGuid>034fe18c-6b6f-4b1a-b889-4dba2e0c8621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifiller+ Subscription'])[1]/preceding::span[2]</value>
      <webElementGuid>ea2886a8-090d-477a-8891-72a88171ac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unifiller+ Member Since'])[1]/preceding::span[4]</value>
      <webElementGuid>6e3c38ae-c73e-4690-b75e-b142e2829cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unifiller+ ID']/parent::*</value>
      <webElementGuid>0404d9f4-759d-44b1-9b33-9a15dcc60a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>aca863e1-cfad-4349-8027-57de562d4850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tcaId' and (text() = 'Unifiller+ ID' or . = 'Unifiller+ ID')]</value>
      <webElementGuid>5b03fa30-1dff-4eac-8bae-93a94a537980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
