<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reset Filters</name>
   <tag></tag>
   <elementGuidId>f2c1bbfd-0232-442b-afd6-e31d59c3f09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.resetFiltersSpan__cwLxB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Reset Filters&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b059dcae-b708-444f-bf4f-fdc36c47b405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resetFiltersSpan__cwLxB</value>
      <webElementGuid>cbf487f6-ff36-4ad4-8c37-a508dc9f8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset Filters</value>
      <webElementGuid>ee1181a3-1057-489f-a3f5-5c4d8df21f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageWrapper&quot;]/div[@class=&quot;resultsListHeader__KK1hJ&quot;]/div[@class=&quot;dropdownContainer__C5fdA&quot;]/div[@class=&quot;resetFilters__A3rQi&quot;]/span[@class=&quot;resetFiltersSpan__cwLxB&quot;]</value>
      <webElementGuid>3407681c-d3e5-4bf2-80f6-524cf8d62574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div[4]/span</value>
      <webElementGuid>1207b32f-09b1-45aa-b204-8d10c9f5a78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan'])[1]/following::span[1]</value>
      <webElementGuid>7cbc5db5-9fcb-4b79-87ea-c223655f8316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sorry! No results found.'])[1]/preceding::span[1]</value>
      <webElementGuid>6643d686-2630-4718-99aa-ae8e1b0e01c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset Filters']/parent::*</value>
      <webElementGuid>ffe018bc-25f0-4f91-b582-b76a6ce8ad7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>a570a149-e2a3-41ee-b16f-dc11ee68f08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reset Filters' or . = 'Reset Filters')]</value>
      <webElementGuid>b7874477-184f-47dc-8b44-1389c211f270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
