<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard</name>
   <tag></tag>
   <elementGuidId>8c9407a3-30ed-43c9-a0bd-6c76b3e14edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.secondary-copy.dashboardpanel_tabText__bebgN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div/aside/div/div[2]/nav/a/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6972cc72-ea0d-4eef-a300-d6dc60ee57fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-copy dashboardpanel_tabText__bebgN</value>
      <webElementGuid>c0aa18bf-7340-4a33-b5a3-8a118bae2cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>e59cfddb-5ac1-41c0-94bb-c25ddf50bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout-wrapper__Voyyt&quot;]/section[@class=&quot;page-wrapper_page-wrapper___qdV9 cart_parent-dashboard-page__5PAwp&quot;]/div[@class=&quot;dashboardpanel_container__P1uFG&quot;]/aside[@class=&quot;dashboardpanel_wrapper__n52tv&quot;]/div[@class=&quot;dashboardpanel_logo-section__cUg3A&quot;]/div[@class=&quot;dashboardpanel_tabs-section__9U5YY&quot;]/nav[1]/a[1]/div[@class=&quot;dashboardpanel_dashboardTabs__n7nSg&quot;]/div[@class=&quot;dashboardpanel_tabContent-wrapper__guD_x&quot;]/div[@class=&quot;secondary-copy dashboardpanel_tabText__bebgN&quot;]</value>
      <webElementGuid>63141a6f-98cd-4193-8000-39c6a32065b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/aside/div/div[2]/nav/a/div/div/div[2]</value>
      <webElementGuid>d22d125a-6d19-4f49-aa60-d6c096d4fb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bookings'])[1]/preceding::div[5]</value>
      <webElementGuid>ef9825c5-4b49-42e2-87a0-5280f08548cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::div[12]</value>
      <webElementGuid>df44a686-22f7-4ae4-bb96-b3ebe49c7192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div[2]</value>
      <webElementGuid>d6ac2b49-bb80-4211-9852-d776f7b1404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>eabd2293-dfb0-493c-b17b-d8745daeace2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
